### ISSUE TITLE
Installation fails on Python 3.10

### ISSUE THREAD

**Issue by gasman** [tkhyn/l18n#8]
Running `pip install l18n==2020.6.1` under Python 3.10.0 on macOS 10.14.6 fails with the following output:

```
Collecting l18n==2020.6.1
  Using cached l18n-2020.6.1.tar.gz (50 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/matthew/.virtualenvs/wagtail310/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/p6/_51b92q88xj9kk0059bc8f3h0000gn/T/pip-install-ec0j8s9h/l18n_9ffec079b1454debad1ec881dc09974e/setup.py'"'"'; __file__='"'"'/private/var/folders/p6/_51b92q88xj9kk0059bc8f3h0000gn/T/pip-install-ec0j8s9h/l18n_9ffec079b1454debad1ec881dc09974e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/p6/_51b92q88xj9kk0059bc8f3h0000gn/T/pip-pip-egg-info-p88jtkev
         cwd: /private/var/folders/p6/_51b92q88xj9kk0059bc8f3h0000gn/T/pip-install-ec0j8s9h/l18n_9ffec079b1454debad1ec881dc09974e/
    Complete output (12 lines):
    Traceback (most recent call last):
      File "/private/var/folders/p6/_51b92q88xj9kk0059bc8f3h0000gn/T/pip-install-ec0j8s9h/l18n_9ffec079b1454debad1ec881dc09974e/setup.py", line 74, in <module>
        cmd_module = getattr(__import__('setuptools.command', fromlist=[cmd]),
    AttributeError: module 'setuptools.command' has no attribute 'bdist_wininst'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/p6/_51b92q88xj9kk0059bc8f3h0000gn/T/pip-install-ec0j8s9h/l18n_9ffec079b1454debad1ec881dc09974e/setup.py", line 78, in <module>
        cmd_module = getattr(__import__('distutils.command', fromlist=[cmd]),
    AttributeError: module 'distutils.command' has no attribute 'bdist_wininst'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/26/14/55b76b4ecbe44f1eb133f5983a2cd0aa1e633d5e34a73f2605d7a20a7ca0/l18n-2020.6.1.tar.gz#sha256=ea7a65b2f0935b14601a3295f2c5e5e8b54126dd1e6a7fef4e44d2b8dd5b695a (from https://pypi.org/simple/l18n/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement l18n==2020.6.1 (from versions: 2014.10.1, 2015.2, 2015.6, 2015.7, 2016.4, 2016.6, 2016.6.1, 2016.6.2, 2016.6.3, 2016.6.4, 2018.5, 2020.6, 2020.6.1)
ERROR: No matching distribution found for l18n==2020.6.1
```

Apparently the bdist_wininst command is now removed: https://docs.python.org/3.10/whatsnew/3.10.html#distutils

**Comment by gasman** [comment]
Yep, that's working well now - thanks!
